# Generated by Django 3.2.4 on 2021-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
