# Generated by Django 3.2.4 on 2021-06-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0004_person_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
