# Generated by Django 3.2.4 on 2021-06-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0006_alter_person_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='givestrapi.day'),
        ),
    ]
