# Generated by Django 3.2.4 on 2021-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0007_alter_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
