# Generated by Django 3.2.4 on 2021-06-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0008_auto_20210611_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
