# Generated by Django 3.2.4 on 2021-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0009_auto_20210611_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['person'], 'verbose_name_plural': 'Availability'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['user'], 'verbose_name_plural': 'Person'},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='on_call',
        ),
        migrations.AddField(
            model_name='person',
            name='on_call',
            field=models.BooleanField(default=True),
        ),
    ]
