# Generated by Django 3.2.4 on 2021-06-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0010_auto_20210611_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='street',
        ),
    ]
