# Generated by Django 3.2.4 on 2021-06-15 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('givestrapi', '0013_gender_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='message',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
